name: "reminder-lint"
description: "Custom action for reminder-lint cli."

inputs:
  args:
    description: Arguments to pass to the reminder-lint.
    default: "run"

outputs:
  stdout:
    description: "The stdout of reminder-lint command."

runs:
  using: docker
  image: ./actions/Dockerfile
  args:
    - ${{ inputs.args }}
