name: "reminder-lint"
description: "Custom action for reminder-lint cli."

inputs:
  args:
    description: Arguments to pass to the reminder-lint.
    required: false
    default: "run"

runs:
  using: docker
  image: ./actions/Dockerfile
  args:
    - ${{ inputs.args }}
