name: 'reminder-lint'
description: 'Custom action for reminder-lint cli.'

inputs:
  args:
    description: Arguments to pass to the reminder-lint.
    required: false
    default: 'run'

runs:
  using: docker
  image: docker://ghcr.io/cyberagent/reminder-lint:latest
  args:
    - ${{ inputs.args }}
