name: "reminder-lint"
description: "Custom action for reminder-lint cli."

inputs:
  args:
    description: Arguments to pass to the reminder-lint.
    default: "run"
  image_tag:
    description: "Docker image tag for reminder-lint."
    default: "latest"

outputs:
  stdout:
    description: "The stdout of reminder-lint command."
    value: ${{ steps.run-lint.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: Run reminder-lint
      id: run-lint
      run: |
        exit_code=0
        output=$(docker run --rm -v ${{ github.workspace }}:/work -w /work ghcr.io/cyberagent/reminder-lint:${{ inputs.image_tag }} ${{ inputs.args }} 2>&1) || exit_code=$?
        
        echo "${output}"
        
        echo "stdout<<EOF" >> $GITHUB_OUTPUT
        echo "${output}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        exit $exit_code
      shell: bash
