[package]
name = "reminder-lint-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reminder-lint-core = { path = "../core" }
anyhow = { version = "1.0.82" }
argh = "0.1.10"
promptuity = "0.0.5"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.33"
