name: CI

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - "main"
  pull_request:
    types: [synchronize, opened, reopened]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: cargo build
      - run: cargo test

  format_check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: cargo fmt --all -- --check

  clippy_check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: cargo clippy --all-targets --all-features --no-deps

  pass:
    runs-on: ubuntu-24.04
    needs:
      - build_and_test
      - format_check
      - clippy_check
    steps:
      - run: exit 0
