name: Release

permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version"
        type: string

jobs:
  tag-version:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    outputs:
      tag: ${{ github.event.inputs.version }}
      tag-flag: ${{ format('--tag={0}', github.event.inputs.version) }}
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Validate input
        run: |
          if [[ "${{ github.event.inputs.version }}" =~ ^v ]]; then
            echo "Error: version must not start with 'v'"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85

      - name: Install cargo-release
        run: cargo install cargo-release --locked

      - name: Cargo release version
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          cargo release version --execute --no-confirm ${{ github.event.inputs.version }}

      - id: git-cliff
        name: Generate the changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose --tag "${{ github.event.inputs.version }}"
        env:
          OUTPUT: CHANGELOG.md

      - name: Cargo release commit
        env:
          PR_BODY: ${{ steps.git-cliff.outputs.content }}
        run: |
          git checkout -b release-${{ github.event.inputs.version }}
          git add CHANGELOG.md
          cargo release commit --execute --no-confirm
          git push -u origin HEAD
          git fetch origin main
          gh pr create --title "Release ${{ github.event.inputs.version }}" --body "$PR_BODY"

          git tag "${{ github.event.inputs.version }}"
          git push origin "${{ github.event.inputs.version }}"
